import { Listing, Property } from "./types/listing";

export const featuredProperties: Listing[] = [
  {
    _id: "6426e982a0f02d9a43e3b64d",
    title: "A nice house for sale in Baxtiari Street",
    description:
      "A beautiful 2-bedroom, 2-bathroom house, with a total area of 200 square meters, is now available for sale in Baxtiari Street, Sulaymaniyah. This active listing features a spacious living area, modern kitchen, and comfortable bedrooms. The house is well-maintained and ready for its new owners. Its prime location in Aqary Street makes it a perfect choice for those looking for easy access to local amenities and a convenient lifestyle. this is a great opportunity to own a wonderful home in a sought-after location.",
    price: 313333,
    status: "featured",
    area: 150,
    rooms: { bedrooms: 1, bathrooms: 4, other: 3 },
    images: [
      "https://cdn.pixabay.com/photo/2016/11/29/03/53/house-1867187_1280.jpg",
      "https://cdn.pixabay.com/photo/2016/11/18/17/46/house-1836070_1280.jpg",
      "https://cdn.pixabay.com/photo/2016/12/30/07/59/kitchen-1940175_1280.jpg",
      "https://cdn.pixabay.com/photo/2014/10/05/22/40/family-home-475879_1280.jpg",
    ],
    type: "sale",
    buildingType: "apartment",
    geometry: { coordinates: [35.497229, 45.425368] },
    location: { address: "Aspswar Ranch", city: "Slemani" },
    amenities: [
      {
        _id: "63fa198cde46d05a3ccaefcb",
        title: "Heating and cooling systems",
        __v: 0,
      },
      {
        _id: "63fa199ade46d05a3ccaefcf",
        title: "Swimming pool",
        __v: 0,
      },
    ],
    owner: [
      {
        _id: "64173a710b2262d407c91540",
        fullName: "khalidRahim",
        email: "khalid00@test.com",
        phone: "7709999900",
        avatar:
          "https://ui-avatars.com/api/?background=random&name=khalidRahim",
        isVerified: false,
        role: "agent",
        createdAt: new Date(),
        updatedAt: new Date(),
        __v: 0,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "6426e8f4624b20924ec35468",
    title: "A nice house for sale in Baxtiari Street",
    description:
      "A beautiful 2-bedroom, 2-bathroom house, with a total area of 200 square meters, is now available for sale in Baxtiari Street, Sulaymaniyah. This active listing features a spacious living area, modern kitchen, and comfortable bedrooms. The house is well-maintained and ready for its new owners. Its prime location in Aqary Street makes it a perfect choice for those looking for easy access to local amenities and a convenient lifestyle. this is a great opportunity to own a wonderful home in a sought-after location.",
    price: 50000,
    status: "normal",
    area: 150,
    rooms: { bedrooms: 1, bathrooms: 4, other: 3 },
    images: [
      "https://cdn.pixabay.com/photo/2016/11/29/03/53/house-1867187_1280.jpg",
      "https://cdn.pixabay.com/photo/2016/11/18/17/46/house-1836070_1280.jpg",
      "https://cdn.pixabay.com/photo/2016/12/30/07/59/kitchen-1940175_1280.jpg",
      "https://cdn.pixabay.com/photo/2014/10/05/22/40/family-home-475879_1280.jpg",
    ],
    type: "sale",
    buildingType: "apartment",
    geometry: { coordinates: [35.497229, 45.425368] },
    location: { address: "Aspswar Ranch", city: "Slemani" },
    amenities: [
      {
        _id: "63fa198cde46d05a3ccaefcb",
        title: "Heating and cooling systems",
        __v: 0,
      },
      {
        _id: "63fa199ade46d05a3ccaefcf",
        title: "Swimming pool",
        __v: 0,
      },
    ],
    owner: [
      {
        _id: "64173a710b2262d407c91540",
        fullName: "khalidRahim",
        email: "khalid00@test.com",
        phone: "7709999900",
        avatar:
          "https://ui-avatars.com/api/?background=random&name=khalidRahim",
        isVerified: false,
        role: "agent",
        createdAt: new Date(),
        updatedAt: new Date(),
        __v: 0,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "6426e87d624b20924ec35461",
    title: "A nice house for sale in Baxtiari Street",
    description:
      "A beautiful 2-bedroom, 2-bathroom house, with a total area of 200 square meters, is now available for sale in Baxtiari Street, Sulaymaniyah. This active listing features a spacious living area, modern kitchen, and comfortable bedrooms. The house is well-maintained and ready for its new owners. Its prime location in Aqary Street makes it a perfect choice for those looking for easy access to local amenities and a convenient lifestyle. this is a great opportunity to own a wonderful home in a sought-after location.",
    price: 50000,
    status: "normal",
    area: 150,
    rooms: { bedrooms: 1, bathrooms: 4, other: 3 },
    images: [
      "https://cdn.pixabay.com/photo/2016/11/29/03/53/house-1867187_1280.jpg",
      "https://cdn.pixabay.com/photo/2016/11/18/17/46/house-1836070_1280.jpg",
      "https://cdn.pixabay.com/photo/2016/12/30/07/59/kitchen-1940175_1280.jpg",
      "https://cdn.pixabay.com/photo/2014/10/05/22/40/family-home-475879_1280.jpg",
    ],
    type: "sale",
    buildingType: "apartment",
    geometry: { coordinates: [35.497229, 45.425368] },
    location: { address: "Aspswar Ranch", city: "Slemani" },
    amenities: [
      {
        _id: "63fa198cde46d05a3ccaefcb",
        title: "Heating and cooling systems",
        __v: 0,
      },
      {
        _id: "63fa199ade46d05a3ccaefcf",
        title: "Swimming pool",
        __v: 0,
      },
    ],
    owner: [
      {
        _id: "64173a710b2262d407c91540",
        fullName: "khalidRahim",
        email: "khalid00@test.com",
        phone: "7709999900",
        avatar:
          "https://ui-avatars.com/api/?background=random&name=khalidRahim",
        isVerified: false,
        role: "agent",
        createdAt: new Date(),
        updatedAt: new Date(),
        __v: 0,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "6426e82c624b20924ec3545c",
    title: "A nice house for sale in Baxtiari Street",
    description:
      "A beautiful 2-bedroom, 2-bathroom house, with a total area of 200 square meters, is now available for sale in Baxtiari Street, Sulaymaniyah. This active listing features a spacious living area, modern kitchen, and comfortable bedrooms. The house is well-maintained and ready for its new owners. Its prime location in Aqary Street makes it a perfect choice for those looking for easy access to local amenities and a convenient lifestyle. this is a great opportunity to own a wonderful home in a sought-after location.",
    price: 50000,
    status: "normal",
    area: 150,
    rooms: { bedrooms: 1, bathrooms: 1, other: 3 },
    images: [
      "https://cdn.pixabay.com/photo/2016/11/29/03/53/house-1867187_1280.jpg",
      "https://cdn.pixabay.com/photo/2016/11/18/17/46/house-1836070_1280.jpg",
      "https://cdn.pixabay.com/photo/2016/12/30/07/59/kitchen-1940175_1280.jpg",
      "https://cdn.pixabay.com/photo/2014/10/05/22/40/family-home-475879_1280.jpg",
    ],
    type: "sale",
    buildingType: "apartment",
    geometry: { coordinates: [35.561498, 45.376761] },
    location: { address: "Near Dafarmw Restaurant", city: "Slemani" },
    amenities: [
      { _id: "63fa197bde46d05a3ccaefc9", title: "Parking", __v: 0 },
      {
        _id: "63fa198cde46d05a3ccaefcb",
        title: "Heating and cooling systems",
        __v: 0,
      },
      {
        _id: "63fa199ade46d05a3ccaefcf",
        title: "Swimming pool",
        __v: 0,
      },
    ],
    owner: [
      {
        _id: "63fa95b6b0b75e64a62289bd",
        fullName: "Akar Mohammed",
        email: "akar@gmail.com",
        phone: "+9647503174475",
        avatar:
          "https://ui-avatars.com/api/?background=random&name=Akar Mohammed",
        isVerified: false,
        role: "agent",
        createdAt: new Date(),
        updatedAt: new Date(),
        __v: 0,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "6426e7f4624b20924ec35458",
    title: "A nice house for sale in Baxtiari Street",
    description:
      "A beautiful 2-bedroom, 2-bathroom house, with a total area of 200 square meters, is now available for sale in Baxtiari Street, Sulaymaniyah. This active listing features a spacious living area, modern kitchen, and comfortable bedrooms. The house is well-maintained and ready for its new owners. Its prime location in Aqary Street makes it a perfect choice for those looking for easy access to local amenities and a convenient lifestyle. this is a great opportunity to own a wonderful home in a sought-after location.",
    price: 32000,
    status: "normal",
    area: 200,
    rooms: { bedrooms: 1, bathrooms: 1, other: 3 },
    images: [
      "https://cdn.pixabay.com/photo/2016/11/29/03/53/house-1867187_1280.jpg",
      "https://cdn.pixabay.com/photo/2016/11/18/17/46/house-1836070_1280.jpg",
      "https://cdn.pixabay.com/photo/2016/12/30/07/59/kitchen-1940175_1280.jpg",
      "https://cdn.pixabay.com/photo/2014/10/05/22/40/family-home-475879_1280.jpg",
    ],
    type: "sale",
    buildingType: "house",
    geometry: { coordinates: [35.567018, 45.394046] },
    location: { address: "1234 Baxtiarit", city: "Slemani" },
    amenities: [
      { _id: "63fa197bde46d05a3ccaefc9", title: "Parking", __v: 0 },
      {
        _id: "63fa198cde46d05a3ccaefcb",
        title: "Heating and cooling systems",
        __v: 0,
      },
    ],
    owner: [
      {
        _id: "63fa95b6b0b75e64a62289bd",
        fullName: "Akar Mohammed",
        email: "akar@gmail.com",
        phone: "+9647503174475",
        avatar:
          "https://ui-avatars.com/api/?background=random&name=Akar Mohammed",
        isVerified: false,
        role: "agent",
        createdAt: new Date(),
        updatedAt: new Date(),
        __v: 0,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "6426e0d57cdc22feb14cb450",
    title: "A nice house for sale in Nali Street",
    description:
      "A beautiful 2-bedroom, 2-bathroom house, with a total area of 200 square meters, is now available for sale in Baxtiari Street, Sulaymaniyah. This active listing features a spacious living area, modern kitchen, and comfortable bedrooms. The house is well-maintained and ready for its new owners. Its prime location in Aqary Street makes it a perfect choice for those looking for easy access to local amenities and a convenient lifestyle. this is a great opportunity to own a wonderful home in a sought-after location.",
    price: 25000,
    status: "normal",
    area: 100,
    rooms: { bedrooms: 1, bathrooms: 1, other: 3 },
    images: [
      "https://cdn.pixabay.com/photo/2016/11/29/03/53/house-1867187_1280.jpg",
      "https://cdn.pixabay.com/photo/2016/11/18/17/46/house-1836070_1280.jpg",
      "https://cdn.pixabay.com/photo/2016/12/30/07/59/kitchen-1940175_1280.jpg",
      "https://cdn.pixabay.com/photo/2014/10/05/22/40/family-home-475879_1280.jpg",
    ],
    type: "sale",
    buildingType: "house",
    geometry: { coordinates: [35.566551, 45.386761] },
    location: { address: "1234 Main Street", city: "Slemani" },
    amenities: [
      { _id: "63fa197bde46d05a3ccaefc9", title: "Parking", __v: 0 },
      {
        _id: "63fa198cde46d05a3ccaefcb",
        title: "Heating and cooling systems",
        __v: 0,
      },
      {
        _id: "63fa1994de46d05a3ccaefcd",
        title: "Internet and cable TV connectivity",
        __v: 0,
      },
      {
        _id: "63fa199ade46d05a3ccaefcf",
        title: "Swimming pool",
        __v: 0,
      },
    ],
    owner: [
      {
        _id: "63fa95b6b0b75e64a62289bd",
        fullName: "Akar Mohammed",
        email: "akar@gmail.com",
        phone: "+9647503174475",
        avatar:
          "https://ui-avatars.com/api/?background=random&name=Akar Mohammed",
        isVerified: false,
        role: "agent",
        createdAt: new Date(),
        updatedAt: new Date(),
        __v: 0,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
];
